### ISSUE TITLE
SagaView: Time indicated on the timeout messages are incorrect

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#281]
**Steps to repro**
1. Run the video store sample (add the SagaAudit plugin to the VideoStore.Sales endpoint).
2. Run the sample to initiate the full message flow.
3. Inspect the Saga view in ServiceInsight and see that the saga requests the timeout for 20seconds. 
4. Both the message that goes out for the timeout and the one in, has the same time. The one that is coming in to the saga should be 20seconds later.

![image](https://f.cloud.github.com/assets/854553/2464490/a5483b50-af97-11e3-97c9-4598611fb82c.png)

**Comment by johnsimons** [comment]
So after looking more into this it looks like the time displayed is correct the wrong datetime is the one on the right hand side when the timeout is received:
![image](https://cloud.githubusercontent.com/assets/122651/7742131/2e0a0112-ffce-11e4-97da-a176c7110336.png)

**Comment by johnsimons** [comment]
So after a bit of investigation the datetime displayed is the `senttime`, see:
![image](https://cloud.githubusercontent.com/assets/122651/7790199/d914d906-02c1-11e5-880e-1f6570b455f3.png)

So:
1. is the sent time for that message
2. is the received time
3. is the sent time

**Comment by indualagarsamy** [comment]
@johnsimons - I'd argue that 1 needs to be Received time as opposed to Sent Time.
For 3, it makes perfect sense to show SentTime.

**Comment by johnsimons** [comment]
So not sure what to do here ? @indualagarsamy

**Comment by johnsimons** [comment]
@indualagarsamy but then 1. and 2. would be the same ?

**Comment by indualagarsamy** [comment]
I think that's ok in my opinion. - Because, that's also the time the saga is processing the message.

**Comment by johnsimons** [comment]
> I think that's ok in my opinion. - Because, that's also the time the saga is processing the message.

Not sure @indualagarsamy, I actually like the senttime, mostly because then we have three different datetimes being displayed, no repetition

**Comment by johnsimons** [comment]
@Particular/engineers thoughts on the datetimes displayed in the diagram, what makes more sense, see https://github.com/Particular/ServiceInsight/issues/281#issuecomment-105079730 for context

**Comment by indualagarsamy** [comment]
If the saga diagram is comprised of 3 parts: 
- what the saga receives (left)
- how that changes the saga data (in the middle)
- what messages get sent out as a result (in the right), 
then showing the received time on the message on the left makes more sense to me that the sent time.

**Comment by DavidBoike** [comment]
Having 3 DateTimes is not altogether that useful because it's really hard for your brain to compare them in any meaningful way unless they're monospace and right on top of each other. Then it's STILL hard. That's why relative time JS libraries are so popular.

The diff between 2 and 3 is really somewhat meaningless. Most of the time there will be a second or two difference, tops. If it's bigger, that just means that your saga handler is being naughty and doing more than the recommended "messages in, make decisions, messages out." So then it's just extra pixels, and more noise.

And I'm not really sure that the diff between 1 and 2 is relevant for a saga view. Building on what @indualagarsamy said, about the 3 parts, the goal of this diagram is to understand how the saga changes as it reacts to what it receives, not how long any of that takes.

Crazy idea: What if 2 was the only DateTime that was displayed?

**Comment by SeanFeldman** [comment]
@DavidBoike not so crazy. 1 - the receive time is important when looking from a higher level. When messages came in or got sent out probably could indicate that you're drilling into messages details therefore concentrating on a "slice" of your saga rather than entire flow.

**Comment by johnsimons** [comment]
@DavidBoike :+1: to only display 2

**Comment by distantcam** [comment]
There's been no movement on this in over a year. Closing.
