### ISSUE TITLE
SI is not checking for license installed in HKLM

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#342]
License can be installed in one of many ways. And one way is to install it under HKLM.
However, SI does not recognize a valid license, when installed under HKLM and even though a valid license is present in HKLM, it prompts with a license expired dialog just based on HKCU.

**NOTE:** If this is a 64 bit OS, then please ensure that the license is also added under `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\ParticularSoftware`
## 

Currently, the check does this:
https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight.Desktop/Core/Licensing/AppLicenseManager.cs#L13

It also needs to check HKLM. Here's the code from NServiceBus:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Licensing/LicenseManager.cs#L111-121

**Comment by trygvelo** [comment]
I have the same problem with the newest version of ServiceInsight (1.4.0, ServiceControl 1.6.3). License was in HKLM but ServiceInsight would nag about trial expired. I added License to HKCU and it works fine. 

Probably unrelated, but might be of interest: My newest endpoint deployments are explicitly referencing a license file path in app.config appSettings (<add key="NServiceBus/LicensePath" value="C:\License\License.xml" />) and the older are implicitly using the HKLM in 64 bit registry. I have a 32 bit endpoint as well which uses the 32 bit registry key in HKLM and it works fine, but I'll change to the app.config approach since I think it is easier to just change the license file in one location.
