### ISSUE TITLE
Saga View: selected message is not highlighted

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#364]
### Explanation
- When a message is selected in the message list, its is also highlighted in the Message Flow view:

![image](https://cloud.githubusercontent.com/assets/3889023/3604783/fbd15bb6-0d23-11e4-93a7-f9b51ce9362b.png)
- The same message selection & highlighting model should be applied to Saga View, like this:

![image](https://cloud.githubusercontent.com/assets/3889023/3604800/1e2519b4-0d24-11e4-9d85-51c1831af09a.png)
- However, currently, this selection is not performed in the Saga View 
  - (in the above image I manually selected the messages in Saga View, but if I change message selection in Message List, the highlighting of the currently selected message in Saga View will not be updated / displayed)
### Why is this valuable ?

It is valuable in cases when you move between views and / or arrange views for side-by-side display. 
In such cases highlighting the currently selected message allows quick user focus on a consistent context.

**Comment by distantcam** [comment]
Ok, here's the problem.

In SI we have a `StoredMessage` object, which represents the currently selected message. When that changes the Saga view keeps the messageId and uses the sagaId to get the saga info from SC.

That saga info contains `SagaMessage` objects for each message shown in the diagram. This is a smaller version of the info from the message list, and since it's from SC we don't control what data it has.

To then change the selected message for the system we need a full `StoredMessage` object, but we only have a `SagaMessage` object. Square peg, meet round hole.

Potential solutions are:

- Fire a `SelectedMessageIdChanged` event with just the messageId. Then the message list can look for that message, and fire the full `SelectedMessageChanged` event. This only works if the new message is in the currently displayed page of messages.

- Rewrite the selection system to use messageId instead. The problem here is not everything cares about the messageId. For example the endpoint list only cares about the endpoint of the selected message.

**Comment by HEskandari** [comment]
Something else that just came to my mind: Would it be possible to create a 'partial' `StoredMessage' object for the purpose of changing the selection and making the interfaces compatible?

If the Message List is custom a collection of `StoredMessage` and we tweak the `.Contains` to check the collection by `Id` rather than by reference, would that solve the issue? 

Here's the flow:

- SagaView would create a partially filled `StoredMessage` and publish an event.
- MessageList gets that event, search in its internal list of messages by checking if any of them match the ID of the `StoredMessage` object in the event.
- If found,  MessageList would set that fully populated object as the current selection.

**Comment by sergioc** [comment]
Description from [duplicate](https://github.com/Particular/ServiceInsight/issues/701):

>There could be different scenarios where Messages window contains no data, or different selected row but Saga View still shows a diagram or shows a different message's diagram.
>
>- Perform a search in Messages window that yield no result, e.g. search by a non-existing keyword. The Messages window shows no messages as expected, but the Saga view shows the first (hidden) message's saga diagram.
>
>- Select a message in Messages window and notice the Saga view opens the correct diagram. Perform a search in Messages window that yields no result. Change the Order of the Message view, e.g. sort by MessageType column. Clear the search so the view refreshes with data but observe the wrong diagram being displayed in the Saga view.
>
>It looks like in certain scenarios `Current Selection` does not flow through Saga view.

**Comment by HEskandari** [comment]
The selection is in sync with Saga view. 

![image](https://user-images.githubusercontent.com/132117/91674778-64096c80-eb7d-11ea-8127-88d101b75a1a.png)
