### ISSUE TITLE
Visualize vertical connecting lines from handler

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#395]
1. Vertical connecting lines are visualized on-hover (see below)
* They are visible only when the message is selected / highlighted or on-hover
* If vertical lines will be displayed when messages are not highlighted, the result may be confusing:
   * different line types (timeout, event, command) overriding each other
   * lines crossing over handlers

![image](https://cloud.githubusercontent.com/assets/3889023/4522225/1079debc-4d25-11e4-9c8c-3608e3da844b.png)

**Comment by sergioc** [comment]
Continuing discussion from https://github.com/Particular/Requirements/issues/190, original comment from @udidahan:

>The way that the lines flow in the sequence diagram just doesn't work for me. 

>![image](https://cloud.githubusercontent.com/assets/475886/6027303/bd5d13ba-abe9-11e4-8e6e-7a1a3a11d339.png)

>I find the fact that there are lines that come out of an endpoint line without a rectangle confusing. I'd much rather have a more regular looking sequence diagram - like [this](http://www.tracemodeler.com/articles/pimp-my-diagram-three-little-pigs/img/original-sequence-diagram-by-ken-howard.png):

>![image](https://cloud.githubusercontent.com/assets/475886/6027420/a2151a3e-abea-11e4-8f8c-5ae01705c701.png)

>I believe that using the vertical (top to bottom) axis to represent the delivery time of the message just complicates the diagram.

>I believe that it would be better to have the arrows go horizontally only. Representing delivery time can be done with some text on top of the arrow - possibly only visible on hover.

**Comment by sergioc** [comment]
@udidahan @dannycohen @indualagarsamy 

Still need some additional discussion here. One thing is for sure, the current implementation is far from ideal since it requires significant effort to understand relationships in the diagram.

Seems like the question here is about whether we should have a diagram with a *regular sequence of events*  ([see previous comment](https://github.com/Particular/ServiceInsight/issues/395#issuecomment-75935754)) or show a *complete temporal sequence of events* (what we’ve been attempting to do in SI).

**Looking at the qualities of using the concept of *regular sequence of events*:**
- + easier to visualize
- + easier to implement
- + more familiar representation
- + potential for better representing sagas (see Udi’s proposal @ https://github.com/Particular/ServiceInsight/issues/395#issuecomment-60350078)
- - does not show a complete sequence of events if we see the receiving parts as events to be discriminated in the sequence
- - limits ability to grow this feature in the future (e.g. add ability to scale timeline)
- - less differentiation between Flow and Sequence diagram views

##Questions:

@dannycohen’s [reasons](https://github.com/Particular/ServiceInsight/issues/395#issuecomment-59738132) for sticking with the concept of a *complete temporal sequence of events* seem quite logical to me, wondering how others think about it?

How about a temporary compromise that allow us to quickly bring out an acceptable result?:
- implement an additional *regular sequence* view
- add “regular / temporal” toggle in UI
- further refine the *complete temporal sequence* in the meanwhile

Thoughts?

**Comment by udidahan** [comment]
@sergioc what we're discussing here is the plan of attack for the [requirement](https://github.com/Particular/Requirements/issues/190) so let's continue that over there. Thanks.

**Comment by sergioc** [comment]
Moving discussion to https://github.com/Particular/Requirements/issues/190, as per new Requirements process and closing this issue as agreed with @distantcam
