### ISSUE TITLE
Clicking the link that opens the popup does not select the message

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#471]
![2015-06-22 12_20_31-serviceinsight for nservicebus](https://cloud.githubusercontent.com/assets/122666/8274676/20cbf2c0-18d9-11e5-8e8b-84461c0ade8c.png)

**Comment by HEskandari** [comment]
It is not just about disabled Retry message menu. If you click anywhere on the opened popup, the selected message would change. At least that was the designed behavior. 

After testing this a bit, I can see that clicking the link to open the popup would not initially select the right message and that would cause the confusion. I'll change the behavior so that it does.
