### ISSUE TITLE
ServiceInsight does not provide feedback to the user when a license is validated

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#502]
The license error message should contain information about which condition has not been met to help the customer in identifying the license issue. The error messages should be displayed in ServiceInsight when importing the license.

**Comment by colin-higgins** [comment]
@ramonsmits @Particular/serviceinsight 
Another customer with this problem.

**Comment by colin-higgins** [comment]
@Particular/serviceinsight I would argue that this should be classified as a bug. If the UpgradeProtectionExpired date is bad, the user never has a chance to import a new license as the application quits immediately. 

I would think they should have the option to import a new license.

**Comment by boblangley** [comment]
This issue was referenced on our Google Group: https://groups.google.com/d/msgid/particularsoftware/72edb675-60d5-4f25-aca0-d3502fc61408%40googlegroups.com

**Comment by boblangley** [comment]
This is marked as a feature, but appears to be a bug. The problem seems to be that once an expired / invalid license is imported the user does not have a friendly way to correct it once a valid license is obtained. Can we change the title and description?

**Comment by distantcam** [comment]
Yes I think this is worth escalating to a bug. The reason why it was labeled a feature was because features are anything that are not bugs.

**Comment by HEskandari** [comment]
Here's a summary of what we discussed:

- When evaluating license expiry, there are two values at play: Expired Date and Upgrade Protection. This is due to how SI is marketed and sold (enterprise license vs. perpetual)
- Customers on perpetual license can upgrade to the versions released prior to Upgrade Protection expiry date. Currently, if they upgrade beyond that date, the application will *not* launch. They message they get is license expired. They wouldn't know they have to downgrade and which version to downgrade to.
- The version to date mapping can be inferred from the [Github Release page][2], if a link / guidance is provided.

There is a [Platform Dev issue][1] open for aligning the licensing behaviors across the products but the maintainers group is looking for a fix as an interim solution, with an eye on future requirements.

The maintainers group would like to follow a similar approach to NServiceBus core where it doesn't shutdown when the valid license can not be found. To achieve this in the context of a desktop application, we have decided to change ServiceInsight to a "nagware" with potential of limiting the functionalities in future. Basically, if a trial is expired, proper license can not be found or upgrade protection has expired, we display a nag screen. The information in the nag screen can guide the user to take an action, e.g. in case of Upgrade Protection expiration, we can provide guidance to the user to downgrade to the latest allowed release. This would allow users to:

- Keep running SI in case of emergencies until they upgrade.
- Have a clear path to downgrade, in case of accidental upgrades (auto updates, PI updates, manual updates).
- Allow them to try a new release/patch that they wouldn't be able to otherwise, before they decide if they should upgrade.

Please provide your comments here.

[1]: PlatformDevelopment/issues/481
[2]: github.com/Particular/serviceInsight/releases

**Comment by gbiellem** [comment]
:+1:  Seems sensible

**Comment by boblangley** [comment]
So are we only showing the nagware screen until they downgrade?

**Comment by gbiellem** [comment]
@boblangley I think what you getting at is that there should be some indication in the old copy of SI that the maintenance has expired. Correct?

**Comment by boblangley** [comment]
As I understand it, now the software has the potential to just not work at all. The proposal is to allow the software to launch, but show a nagware license window. With this proposed solution can they just click past it and continue using SI?

**Comment by johnsimons** [comment]
@boblangley yes that is exactly the proposal

**Comment by johnsimons** [comment]
@HEskandari I think is worth expanding on how exactly you propose to handle the case of Upgrade Protection expiration

**Comment by HEskandari** [comment]
@boblangley If I understand correctly, yes they can continue using the unlicensed software if they choose to, similar to how they can ignore license warnings when it is expired in NServiceBus.

**Comment by johnsimons** [comment]
IMHO, as a user I would like to be told at install time that my Upgrade Protection has expired, so i don't have to go through the pain of upgrading to them downgrade it

**Comment by gbiellem** [comment]
@johnsimons IMO the product should also indicate that the maintenance or license has lapsed, not just the installer.

**Comment by johnsimons** [comment]
> IMO the product should also indicate that the maintenance or license has lapsed, not just the installer.

Yes and it should warn the users even before it expires

**Comment by HEskandari** [comment]
@johnsimons that's what we need to do in Platform Installer and more around the process of upgrading the products. The purpose of this is how to deal with the situation where you are *somehow* updated your version past the allowed version.

What I propose is:

-If license is expired (trial or otherwise), show a nag screen with a link to renew the license.
-If upgrade protection is expired, show a nag screen with a different message and a link to take them to Github Releases page. They'll need to lookup at their license, check the upgrade protection expiration date and do the math to see which version was the last version they're allowed to run.

**Comment by HEskandari** [comment]
> IMO the product should also indicate that the maintenance or license has lapsed, not just the installer.

> Yes and it should warn the users even before it expires

:+1: I like that.

**Comment by gbiellem** [comment]
Any out of maintenance warning should be less intrusive than an out of license nag screen.  
It's not a error condition it just limits your ability to upgrade.

**Comment by boblangley** [comment]
> Any out of maintenance warning should be less intrusive than an out of license nag screen.

:+1: I would suggest we even split that part out as a separate enhancement feature so it can be prioritized separately.

>-If license is expired (trial or otherwise), show a nag screen with a link to renew the license.
>-If upgrade protection is expired _**and they have installed an invalid version**_, show a nag screen with a different message and a link to take them to Github Releases page. They'll need to lookup at their license, check the upgrade protection expiration date and do the math to see which version was the last version they're allowed to run.

 :+1: for the nag screen as @HEskandari proposed. As an additional split out feature enhancement could we can figure this out how for them?

**Comment by willie-levy** [comment]
Just as a question, what would be involved in somehow not allowing the upgrade in the first place if the client isn't entitled to it? this way preventing clients with a lapsed Upgrade protection (but a perpetual license) getting the license expired screen?

**Comment by boblangley** [comment]
>Just as a question, what would be involved in somehow not allowing the upgrade in the first place if the client isn't entitled to it? this way preventing clients with a lapsed Upgrade protection (but a perpetual license) getting the license expired screen?

I think we agree that should be done as well (as proposed by @HEskandari  and @johnsimons), but should be done as another issue so it can be scoped separately.

**Comment by HEskandari** [comment]
@boblangley :+1: on separating the enhancements to a separate feature request. I'll create one for that.

**Comment by KimberlyA** [comment]
@HEskandari 

**If upgrade protection is expired, show a nag screen with a different message and a link to take them to Github Releases page. They'll need to lookup at their license, check the upgrade protection expiration date and do the math to see which version was the last version they're allowed to run.**

Is there a way to give them a specific message instead of having them check that their UP is valid?  A lot of times, the person who writes in saying that they are receiving the error messages has no idea that the UP has expired (just had this case over the weekend) as they weren't involved in the purchasing or renewal.  Could the popup say "Your upgrade protection has expired, please contact your licensing administrator (or whatever the role is of the person who has purchased the license on their end) or something like that?  This would allow for more communication within their team.

**Comment by HEskandari** [comment]
@KimberlyA Sure, we can use a wording that works best communication wise. 

This aside, do you think it helps if we show the license expiration / UP expiration in the About / License Window of the ServiceInsight? As you say, they won't notice because we don't show the expiration anywhere and it may be stored in Windows Registry making it non-obvious.

**Comment by KimberlyA** [comment]
@HEskandari i think thats a great idea.  it's not a secret so i don't see any reason why we wouldn't want to show it and this way they know exactly what the reason is that it's not working.

**Comment by HEskandari** [comment]
After discussion with @Particular/serviceinsight-maintainers we decided that only the nagware related work should be focus of this issue and the other enhancements should be part of #569.

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers If we don't close the app after a valid license can not be found, we're already displaying the registration dialog. Isn't that enough to act as a nag screen? Do we need a specific dialog for the nag screen? I think that would be too much.

If we decide to go with the registration dialog, we need to decide the following:

 - Which buttons should be visible (currently we have these buttons: Contact Sales, Purchase, Browse...)
 
 - What should be the displayed text? The text should be generic enough to cover a Trail license expired, a commercial license expired or upgrade protection expired and no license found at all. Currently the text is: "Please click 'Contact Sales' to request an extension to your free trial, or click 'Buy Now' to purchase a license online. When you receive your license file, save it to disk and then click the 'Browse' button to select it."
 
 - What should be title of the dialog? (Currently: ServiceInsight - License Expired)

**Comment by DavidBoike** [comment]
Is this still in progress? Had a customer via live chat with this problem again today.

**Comment by adamralph** [comment]
@DavidBoike AFAIK we're not actively working on it right now, but it sounds like we perhaps should be. @Particular/serviceinsight-maintainers thoughts?

**Comment by WilliamBZA** [comment]
@ramonsmits The "Browse" button for importing licenses is always visible now - regardless of the license installed, so I think that this issue is no longer applicable as the user can install new licenses whenever the dialog pops up.

The upgrade protection expiration date is also currently only compared to the release date of the current application. So if the normal Expiration date is in the future (i.e. the license is still valid) they will be shown the expired license dialog if they are using a version of ServiceInsight that is released after their upgrade protection has expired - even if their actual license expiration is set to be in the future. In this scenario they are trying to use a version of ServiceInsight they are not licensed for.

Happy for us to close this?

/cc @DavidBoike

**Comment by ramonsmits** [comment]
>  In this scenario they are trying to use a version of ServiceInsight they are not licensed for.

@WilliamBZA The issue is not that they have an incorrect license, the issue is that the user is not informed the reason why the license isn't valid.

If you say that now the feedback about the invalid license is addressed so that the user knows how to resolve their license issue then this issue can be closed.

**Comment by WilliamBZA** [comment]
The feedback given to the user has not changed, but they now have the option to import a new license when the dialog shows.

I guess that means this stays open.

**Comment by ramonsmits** [comment]
@WilliamBZA I think we should show the reason for license expiration. Not only that it is expired without details. If the maintainers think so too then please leave it open. If not, then please state the reason for withdrawing and close.

**Comment by timbussmann** [comment]
A customer had this issue recently as well. Selecting an outdated license via the browse button seems like it does nothing when the license in no longer valid (the upgrade protection date expired) but there is no hint about this problem at all.

**Comment by HEskandari** [comment]
I have raised #803 to resolve this. It now shows all the errors raised during license validation when you import a license via Register menu.
