### ISSUE TITLE
Sequence Diagram Drill-Down into endpoint to enhance the troubleshooting experience 

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceInsight#509]
After working through ideas presented here https://github.com/Particular/PlatformDevelopment/issues/475 we have decided to explore the troubleshooting experience within an Endpoint.

Notionally a user would have been investigating message flow in the sequence diagram and then decided to Drill-down into a single **_LOGICAL**_ endpoint to look at message processing behaviour at that level.

**Comment by udidahan** [comment]
Adding to that, it's most likely that the drill-down would happen for a specific message at a specific logical endpoint. Physical endpoint instance isn't particularly interesting - though the version of the code processing a message would be, and that may vary from one endpoint instance to another due to a rolling upgrade process.

**Comment by mauroservienti** [comment]
The latest available version of ServiceInsight, 2.3.0, introduced a change so that only logical endpoints are listed in a sequence diagram. The endpoint instance, that handled the message, is visualized in the tool tip shown when selecting a message in the diagram.
