### ISSUE TITLE
Unable to see more than one page of information, when an endpoint is selected

### ISSUE THREAD

**Issue by gamblen** [Particular/ServiceInsight#844]
I have noticed a problem in a recent release of ServiceInsight, if you select an endpoint, then try navigating to the next page it doesn't work.

In Endpoint Explorer, select the server

http://servername:33333/api/messages -- All ok here

Then select page 2

http://servername:33333/api/messages?include_system_messages=False&per_page=50&sort=time_sent&direction=desc&page=2 -- Loading fine
 
In Endpoint Explorer, select an endpoint

http://servername:33333/api/endpoints/ENDPOINT.NAME/messages/  -- All good

Then select page 2

http://servername:33333/api/endpoints/{endpoint}/messages?include_system_messages=False&per_page=50&sort=time_sent&direction=desc&page=2  -- Nothing.

I assume it is because it is requesting {endpoint} rather than ENDPOINT.NAME

**Comment by mikeminutillo** [comment]
Thanks for raising this @gamblen 

You are correct that this is because we are replacing the variable in the template. There is an issue for it in the ServiceControl repository as ServiceControl generates these links https://github.com/Particular/ServiceControl/issues/1808

We will be working on a fix for this soon.

**Comment by timbussmann** [comment]
@gamblen the issue has been fixed in ServiceControl. The paging in ServiceInsight should work again after updating ServiceControl to 4.5.2.

Thanks for reporting the issue!
