### ISSUE TITLE
Message bodies not shown in saga view for message using inheritance

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#855]
A user on our forum asked:

> I wonder why I have an empty message data section in saga visualization section. I can display the message in the Body tab. I use rabbitmq + pgsql.
> ![image](https://user-images.githubusercontent.com/152998/79972386-2a6d7a00-8496-11ea-9a9f-c45e996856ec.png)

Source: https://discuss.particular.net/t/empty-message-data-section-in-saga-visualization/1760

The user-interface should make it clear that the [saga audit plugin](https://docs.particular.net/nservicebus/sagas/saga-audit) is required for state tracking.

**Comment by HEskandari** [comment]
That requires saga plugin to be installed and enabled. It is something different than the messages in the body tab.

**Comment by aph5nt** [comment]
Please check my latest reply here; https://discuss.particular.net/t/empty-message-data-section-in-saga-visualization/1760

**Comment by aph5nt** [comment]
guys, aby update on this?

**Comment by ramonsmits** [comment]
In the saga view these messages are `(Empty)` but can you see the bodies on the **Body** tab?

Can you please share more details on your environment? As @HEskandari mentioned it is not an issue with the saga audit problem.

Which versions of the platform tools are you using? Meaning ServiceInsight, ServiceControl, ServiceControl.Audit, and ServiceControl.Monitoring?

**Comment by aph5nt** [comment]
... it does not work when a message or command or event inherit from some base class
in my case:
```
 public abstract class SagaCommand : ICommand
    {
        protected SagaCommand(string sagaId)
        {
            SagaId = sagaId;
            TimeStamp = DateTime.UtcNow;
        }

        public string SagaId { get; private set; }

        public DateTime TimeStamp { get; private set; }

        public SendOptions GetSendOptions(string destination)
        {
            var options = new SendOptions();
            options.SetDestination(destination);
            return options;
        }
    }
```

**Comment by ramonsmits** [comment]
@aph5nt Thanks for that snippet. That is useful as clearly, we should show the message data for message types that use inheritance. I've flagged it as a bug and we will have it traiged through are bugs process.


However, a few design concerns:

1. Why do you have a "SagaCommand"? sagas are business processes based on events and commands. They should not be identifiable as a "saga" in any message. This leaks implementation details into your message flow which a design smell.
2. Your commands do not need a "TimeStamp" as [a message header already exists that contains the time-sent value](https://docs.particular.net/nservicebus/messaging/headers#diagnostic-and-informational-headers-nservicebus-timesent).
3. Send options are about infrastructure and routing and not advised to make these part of your message logic. It is advised that messages are POCO's focusing on data like DTO's.

**Comment by mikeminutillo** [comment]
@aph5nt we are looking into this issue and trying to replicate it. Do you know which serializer your endpoints are using? The default one will not handle the private properties properly.

If I switch to using the Newtonsoft Json serializer, then I can replicate what you are seeing but I wanted to check if that's what you're using before going too far.

**Comment by mikeminutillo** [comment]
I think I have the answer. When ServiceControl returns a list of messages it modifies the url used to retrieve the message body to append an `instanceId` onto it. This allows subsequent requests from ServiceInsight for the message body to be routed to the correct audit instance in case you have more than one. Unfortunately, the initial saga audit query does not include the `instanceId` query string parameter, and it can't because there is no way for the instance containing the saga data to know which instance the message bodies are in.

To further complicate matters, the ServiceInsight instance uses a local cache for message bodies, so if it has previous retrieved the message body, then some of the message bodies will be shown in the saga audit view and some (which are not cached) will not.

To fix this, we probably need to adjust the query handler in ServiceControl to submit the query to all remote instances if there is no `instanceId` parameter.

**Comment by ramonsmits** [comment]
Fixed by https://github.com/Particular/ServiceInsight/issues/987
