### ISSUE TITLE
No retries audited

### ISSUE THREAD

**Issue by jbakholt** [Particular/ServiceInsight#948]
We've noticed some inconsistencies between what is audited, what is supposed to be audited and what ultimately shows up in Service Insight.

Attached image shows a message that clearly has been retried - but retries remains zero in Service Insight.

I'm not sure but the audit db somewhat confirms this. IsRetried equals 'true':

[AuditDb dump.txt](https://github.com/Particular/NServiceBus/files/5475024/AuditDb.dump.txt)

![Service Insight 2 3 0 Screenshot](https://user-images.githubusercontent.com/8124331/97868370-d6c6cd80-1d0f-11eb-8e20-2285de270799.png)

**Comment by danielmarbach** [comment]
Hi @jbakholt 

Based on my understanding of the codebase the counter is supposed to represent the `NServiceBus.Retries` counter which represents Immediate and Delayed retries but not retries issued by ServiceControl. 

That explains why the counter is zero even though your data is `IsRetried = true`. I do agree though this is slightly misleading. I moved the issue to the ServiceInsight repository. Maybe we can improve this in future releases to make it clearer what the intent is.

**Comment by HEskandari** [comment]
@jbakholt I have raised [this issue](https://github.com/Particular/ServiceControl/issues/2227) two weeks ago to address it. Not all header information is retained by ServiceControl and due to that the number of retries is not stored. Once that's fixed SI would just work and you'd see the correct number of retries (which is the number of times the message is executed and failed within the endpoint).
